name: admin_console
description: Dart starter for Appwrite function.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

   
dependencies: 
  dart_appwrite: ^7.3.0
  dotenv: ^4.1.0
  totempole_services:
    path: "../"
  
      
dev_dependencies:
  lints: ^2.0.1
